### ISSUE TITLE
No module named 'ward2icu.data'

### ISSUE THREAD

**Issue by tb438** [3778/Ward2ICU#1]
When attempting to run run-experiment.py, I am getting the following error:
```
Traceback (most recent call last):
  File "run-experiment.py", line 7, in <module>
    from ward2icu.data import TimeSeriesVitalSigns
ModuleNotFoundError: No module named 'ward2icu.data'
```
Also I didn't notice a dataset in the repo. Where can the dataset be downloaded for this?

Thanks for making your research and model available!

**Comment by ukamath** [comment]
I am getting the same error, how was this resolved?

**Comment by ghost** [comment]
Any updates? From your paper, I was under the impression that the data had been de-identified and made open source (like, wow, what a great resource!). If so, would you let us know about the process to access it?
